from pathlib import Path

from docx import Document

from job_hunting_agent.models import AtsReport, CandidateProfile, Resume
from job_hunting_agent.resume_builder import write_improved_resume


def test_write_improved_resume_creates_final_ats_docx(tmp_path: Path) -> None:
    resume = Resume(
        path="resume.txt",
        text=(
            "PROFESSIONAL EXPERIENCE\n"
            "Senior Data Engineer\n"
            "Tata Consultancy Services | Bengaluru\n"
            "Jan 2020 - Present\n"
            "Built APIs and data pipelines using Python and SQL for analytics workflows.\n"
            "Improved delivery quality by automating validation checks.\n"
            "TECHNICAL SKILLS\n"
            "Skills Python SQL."
        ),
        inferred_skills=("Python", "SQL"),
        inferred_roles=("Python Developer",),
    )
    report = AtsReport(
        score=72,
        strengths=("ATS sections are present.",),
        improvements=("Add measurable achievements.",),
        missing_keywords=("Aws", "Fastapi"),
    )
    profile = CandidateProfile(name="Mriganka Das", target_roles=("Data Engineer",), skills=("Python", "Spark"))

    artifact = write_improved_resume(resume, report, profile, tmp_path)

    docx_path = Path(artifact["docx_path"])
    assert docx_path.exists()
    assert docx_path.suffix == ".docx"
    assert docx_path.parent.name == "improved_resume"
    assert docx_path.name == "Mriganka-Das-ATS-Friendly-Resume.docx"
    assert "pdf_path" not in artifact

    text = "\n".join(paragraph.text for paragraph in Document(str(docx_path)).paragraphs)
    assert "Mriganka Das" in text
    assert "PROFESSIONAL SUMMARY" in text
    assert "CORE SKILLS" in text
    assert "PROFESSIONAL EXPERIENCE" in text
    assert "Senior Data Engineer" in text
    assert "Tata Consultancy Services | Bengaluru" in text
    assert "Jan 2020 - Present" in text
    assert "TECHNICAL SKILLS" in text
    assert "Programming Languages:" in text
    assert "Aws" in text
    assert "ATS-Friendly Resume Template" not in text
    assert "YOUR NAME" not in text
    assert "Skill 1" not in text
    assert "Draft" not in text
    assert "Generated by" not in text
    assert "prompt" not in text.lower()


def test_write_improved_resume_preserves_all_detected_experience_entries(tmp_path: Path) -> None:
    resume = Resume(
        path="resume.txt",
        text=(
            "WORK EXPERIENCE\n"
            "December 2021 - Present | CitiCorp Services India Pvt. Ltd. | Officer\n"
            "Title: GFT\n"
            "Led data workflow automation using Python and SQL for banking processes.\n"
            "September 2020 - December 2021 | Nomura India Services Pvt. Ltd. | Associate\n"
            "Title: Corporate Technology Solution\n"
            "Implemented Spark and Scala data processing for business insights.\n"
            "January 2018 - September 2020 | Capgemini India Ltd., Navi Mumbai | Consultant\n"
            "Title: Yes Bank\n"
            "Developed PL/SQL packages and supported data validation activities.\n"
            "March 2014 - January 2018 | Hexaware Technologies Ltd., Navi Mumbai | Software Engineer\n"
            "Title: Brown Brothers Harriman & Co.\n"
            "Built data uploaders and exporters for downstream reporting systems.\n"
            "PERSONAL DETAILS\n"
            "Languages Known: English, Hindi, Bengali"
        ),
        inferred_skills=("Python", "SQL", "Spark", "Scala"),
        inferred_roles=("Data Engineer",),
    )
    report = AtsReport(score=74, strengths=(), improvements=(), missing_keywords=())
    profile = CandidateProfile(name="Mriganka Das", target_roles=("Data Engineer",), skills=("Python", "SQL"))

    artifact = write_improved_resume(resume, report, profile, tmp_path)

    text = "\n".join(paragraph.text for paragraph in Document(artifact["docx_path"]).paragraphs)
    assert "CitiCorp Services India Pvt. Ltd." in text
    assert "Nomura India Services Pvt. Ltd." in text
    assert "Capgemini India Ltd." in text
    assert "Hexaware Technologies Ltd." in text
    assert "Officer" in text
    assert "Associate" in text
    assert "Consultant" in text
    assert "Software Engineer" in text
