from __future__ import annotations

import textwrap
from pathlib import Path

from .models import AtsReport, CandidateProfile, Resume


def write_improved_resume(resume: Resume, report: AtsReport, profile: CandidateProfile, data_dir: str | Path) -> dict[str, str]:
    output_dir = Path(data_dir) / "improved_resume"
    output_dir.mkdir(parents=True, exist_ok=True)
    base_name = _safe_filename(profile.name or "candidate")
    docx_path = output_dir / f"{base_name}-ats-improved-resume.docx"
    pdf_path = output_dir / f"{base_name}-ats-improved-resume.pdf"

    sections = _resume_sections(resume, report, profile)
    _write_docx(docx_path, sections)
    pdf_written = _write_pdf(pdf_path, sections)

    result = {"docx_path": str(docx_path)}
    if pdf_written:
        result["pdf_path"] = str(pdf_path)
    return result


def _resume_sections(resume: Resume, report: AtsReport, profile: CandidateProfile) -> list[tuple[str, list[str]]]:
    target_roles = ", ".join(profile.target_roles) or ", ".join(resume.inferred_roles) or "Target Role"
    skills = _ordered_terms((*profile.skills, *resume.inferred_skills, *report.missing_keywords))
    summary = (
        f"{profile.name or 'Candidate'} is targeting {target_roles} roles with experience aligned to "
        f"{', '.join(skills[:8]) if skills else 'the configured role requirements'}. "
        "This version highlights ATS-readable sections, role keywords, and measurable impact prompts."
    )
    original_lines = _split_resume_text(resume.text)
    suggested_bullets = [
        "Improved ATS keyword coverage by adding the missing role-specific terms listed below.",
        "Add quantified delivery impact for each major project or role, such as percentage improvement, cost saved, users served, or processing time reduced.",
        "Begin experience bullets with action verbs such as built, automated, improved, led, implemented, designed, and delivered.",
    ]
    if profile.locations:
        suggested_bullets.append(f"Preferred locations: {', '.join(profile.locations)}.")

    return [
        ("Professional Summary", [summary]),
        ("Core Skills", [", ".join(skills) if skills else "Add role-specific skills from target job descriptions."]),
        ("ATS Missing Keywords To Add", list(report.missing_keywords) or ["No configured keywords are missing."]),
        ("Suggested Resume Improvements", list(report.improvements) or ["No major ATS improvements were found."]),
        ("Achievement Bullet Prompts", suggested_bullets),
        ("Original Resume Content", original_lines),
    ]


def _write_docx(path: Path, sections: list[tuple[str, list[str]]]) -> None:
    try:
        from docx import Document
    except ImportError as exc:
        raise RuntimeError("Install DOCX support with: pip install -e '.[docs]'") from exc

    document = Document()
    document.add_heading("ATS Improved Resume Draft", level=0)
    document.add_paragraph(
        "Generated by Job Hunting Agent. Review and edit details before submitting to employers."
    )
    for heading, items in sections:
        document.add_heading(heading, level=1)
        for item in items:
            if heading in {"Core Skills", "Professional Summary", "Original Resume Content"}:
                document.add_paragraph(item)
            else:
                document.add_paragraph(item, style="List Bullet")
    document.save(path)


def _write_pdf(path: Path, sections: list[tuple[str, list[str]]]) -> bool:
    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.pdfgen import canvas
    except ImportError:
        return False

    page_width, page_height = letter
    margin = 54
    y = page_height - margin
    pdf = canvas.Canvas(str(path), pagesize=letter)
    pdf.setTitle("ATS Improved Resume Draft")

    def new_page() -> None:
        nonlocal y
        pdf.showPage()
        y = page_height - margin

    def draw_line(text: str, font: str = "Helvetica", size: int = 10, leading: int = 14) -> None:
        nonlocal y
        if y < margin:
            new_page()
        pdf.setFont(font, size)
        pdf.drawString(margin, y, text)
        y -= leading

    draw_line("ATS Improved Resume Draft", "Helvetica-Bold", 18, 24)
    draw_line("Generated by Job Hunting Agent. Review and edit details before submitting.", size=9, leading=18)
    for heading, items in sections:
        draw_line(heading, "Helvetica-Bold", 13, 18)
        for item in items:
            prefix = "- " if heading not in {"Core Skills", "Professional Summary", "Original Resume Content"} else ""
            for line in textwrap.wrap(prefix + item, width=92):
                draw_line(line)
            y -= 2
        y -= 6
    pdf.save()
    return True


def _split_resume_text(text: str) -> list[str]:
    chunks = textwrap.wrap(text, width=110)
    return chunks[:80] or ["Original resume text could not be extracted cleanly."]


def _ordered_terms(terms: tuple[str, ...]) -> list[str]:
    seen: set[str] = set()
    ordered: list[str] = []
    for term in terms:
        cleaned = term.strip()
        key = cleaned.lower()
        if cleaned and key not in seen:
            seen.add(key)
            ordered.append(cleaned)
    return ordered


def _safe_filename(value: str) -> str:
    cleaned = "".join(char if char.isalnum() or char in "-_" else "-" for char in value.strip())
    return cleaned.strip("-")[:80] or "candidate"
